INSERT OR REPLACE INTO EvolutionType (Id, Name)
VALUES (1, 'Leveling')
      ,(2, 'Leveling with High Friendship')
      ,(3, 'Leveling with Move')
      ,(4, 'Leveling at Location')
      ,(5, 'Leveling at Time')
      ,(6, 'Leveling with Item')
      ,(7, 'Leveling with Specific Gender')
      ,(8, 'Leveling on Specific Game')
      ,(9, 'Leveling with Unique Condition')
      ,(10, 'Leveling with Additional Factors')
      ,(11, 'Stone')
      ,(12, 'Stone with Specific Gender')
      ,(13, 'Trade')
      ,(14, 'Trade with Item')
      ,(15, 'Trade for Pokemon');