INSERT OR REPLACE INTO Pokedex (Id, Code, Name, RegionId)
VALUES (1, 'national', 'National', NULL)
      ,(2, 'kanto', 'Kanto', 1)
      ,(3, 'new', 'New', 2)
      ,(4, 'johto', 'Johto', 2)
      ,(5, 'hoenn', 'Hoenn', 3)
      ,(6, 'hoenn_oras', 'Hoenn ORAS', 3)
      ,(7, 'sinnoh', 'Sinnoh', 4)
      ,(8, 'sinnoh_pt', 'Sinnoh Platinum', 4)
      ,(9, 'unova', 'Unova', 5)
      ,(10, 'unova_n', 'Unova New', 5)
      ,(11, 'kalos_ce', 'Kalos Central', 6)
      ,(12, 'kalos_co', 'Kalos Coastal', 6)
      ,(13, 'kalos_mo', 'Kalos Mountain', 6)
      ,(14, 'alola', 'Alola', 7)
      ,(15, 'alola_u', 'Alola Ultra', 7)
      ,(16, 'galar', 'Galar', 8)
      ,(17, 'galar_isle_of_armor', 'Galar Isle of Armour', 8)
      ,(18, 'galar_crown_tundra', 'Galar Crown Tundra', 8);